// @see https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities
module.exports.ANDROID = 'android'
module.exports.CHROME = 'chrome'
module.exports.FIREFOX = 'firefox'
module.exports.HTMLUNIT = 'htmlunit'
module.exports.INTERNET_EXPLORER = 'internet explorer'
module.exports.IPHONE = 'iPhone'
module.exports.IPAD = 'iPad'
module.exports.OPERA = 'opera'
module.exports.SAFARI = 'safari'
