// @see https://www.w3.org/TR/webdriver1/#dfn-own-properties
// @see https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/Platform.java
module.exports.WINDOWS = 'WINDOWS'
module.exports.XP = 'XP'
module.exports.VISTA = 'VISTA'
module.exports.MAC = 'MAC'
module.exports.LINUX = 'LINUX'
module.exports.UNIX = 'UNIX'
module.exports.ANDROID = 'ANDROID'
